# Generated by Django 5.1.4 on 2025-01-11 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='councilworker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.address'),
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='reading_recorder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='readings.councilworker'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.tenantprofile'),
        ),
    ]
